### ISSUE TITLE
i cant get it to run

### ISSUE THREAD

**Issue by develperbayman** [dille12/OVRDOZE#44]
im on ubuntu on a opi5 i install the requirements.txt that went fine then i ran the RUN.py

im pretty sure i have all the dependencies do i need a .png files?

: xanth@xanths-box:~$ python3 '/var/www/html/OVRDOZE-main/RUN.py' 
pygame 2.1.2 (SDL 2.0.16, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
ovrdoze_data/settings.dat ovrdoze_data/
VALUE INIT
Traceback (most recent call last):
  File "/var/www/html/OVRDOZE-main/RUN.py", line 13, in <module>
    from values import *
  File "/var/www/html/OVRDOZE-main/values.py", line 55, in <module>
    icon = pygame.image.load("texture/icon.png")
FileNotFoundError: No file 'texture/icon.png' found in working directory '/home/xanth'.

**Comment by dille12** [comment]
Seems like that the working directory is not automatically set on the OVRDOZE folder on linux, and I am not really sure how to do that since I use windows. Do you know how to set the working directory manually on Linux?

**Comment by develperbayman** [comment]
when i reference any files in my scripts for example i have a ai script that uses a .wav file for a activation noise from the working directory i reference it with a ./sound.wav  so i imagine even folders in the working directory would be ./<folder_name>/filename

**Comment by dille12** [comment]
All the filenames used in this project are in this format: `icon = pygame.image.load("texture/icon.png")`, which I think means that I should convert those into `icon = pygame.image.load(os.path.join(os.getcwd(), "texture/icon.png"))`. I'll get on this

**Comment by develperbayman** [comment]
im curious has anyone else had this issue? ....but yeah this look cool as hell ...good job

**Comment by dille12** [comment]
I think when multiple people worked on this for a while someone might have been using Ubuntu, but I could be wrong. But thank you! When you have time, can you try the latest commit? It's still going to crash, but if the error message changes, it means that the fix is working

**Comment by develperbayman** [comment]
oh for sure id love to help ill give it a stab here in a little bit and will post my results here

**Comment by develperbayman** [comment]
so i got up running run pretty great left the alley answered the phone bought a mp-5 but i went to go down into the "basement" area and the game just crashed  : Traceback (most recent call last):
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1368, in <module>
    main()
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1228, in main
    s2 = button_sp_new_game.tick(screen, mouse_pos, mouse_single_tick, glitch)
  File "/home/xanth/Desktop/OVRDOZE-main/button.py", line 134, in tick
    return self.action(arg) if arg != None else self.action(self.args)
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 378, in start_sp_career
    app.start_sp(args)
  File "/home/xanth/Desktop/OVRDOZE-main/app.py", line 271, in start_sp
    game.main(
  File "/home/xanth/Desktop/OVRDOZE-main/game.py", line 1056, in main
    if (((time.time() - wave_change_timer > wave_interval) and not SyncSongs) or MInfo.DROP) and map.enemy_type == "zombie":
AttributeError: 'MixInfo' object has no attribute 'DROP'

**Comment by dille12** [comment]
Okay thats great, thats a different problem which is because I have been focusing in the endless mode and not the "Start New Game" option, which has created a lot of problems. Endless mode should now work! Also I tried fixing the working directory issue so it shouldn't occur anymore

**Comment by develperbayman** [comment]
on this snapshot it appears to have reverted to previous issue? 
``` Traceback (most recent call last):
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 13, in <module>
    from values import *
  File "/home/xanth/Desktop/OVRDOZE-main/values.py", line 61, in <module>
    icon = pygame.image.load(fp("texture/icon.png"))
FileNotFoundError: No such file or directory: '/home/xanth/assets/texture/icon.png'.
```

**Comment by dille12** [comment]
Try inputting `cd /home/xanth/Desktop/OVRDOZE-main` or the directory where the RUN.py is, and then running the RUN.py? The script is searching assets from your default working directory, and I don't think I can change it automatically from inside the script

**Comment by develperbayman** [comment]
lol oops my bad, you are correct

**Comment by develperbayman** [comment]
endless mode seems pretty cool it ran it played but on exit was errors and on loading timeout issues but selecting wait worked also endless i think could benifit from a larger map? could you give me a quick run down on the game structure? i know your using pygame never used it before but i would like to add to it also a "take all" would be cool in treasure box menu  :```
 Traceback (most recent call last):
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1369, in <module>
    main()
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1261, in main
    s7_2 = button_start_single_player.tick(screen, mouse_pos, mouse_single_tick, glitch)
  File "/home/xanth/Desktop/OVRDOZE-main/button.py", line 134, in tick
    return self.action(arg) if arg != None else self.action(self.args)
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 395, in start_sp
    app.start_sp(args)
  File "/home/xanth/Desktop/OVRDOZE-main/app.py", line 271, in start_sp
    game.main(
  File "/home/xanth/Desktop/OVRDOZE-main/game.py", line 2169, in main
    quit_button_alt.tick(screen, mouse_pos, click_single_tick, glitch)
  File "/home/xanth/Desktop/OVRDOZE-main/button.py", line 134, in tick
    return self.action(arg) if arg != None else self.action(self.args)
  File "/home/xanth/Desktop/OVRDOZE-main/game.py", line 82, in quit
    RUN.main()
  File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 984, in main
    if app.pygame.mouse.get_pressed()[0] and clicked == False:
UnboundLocalError: local variable 'clicked' referenced before assignment
```

**Comment by develperbayman** [comment]
im wondering if there is a tool like this is could use to make maps? : https://www.pygame.org/project-Map+Editor-2868-.html

**Comment by dille12** [comment]
Actually yeah, there is a tool inside the game which allows you to create walls and the navigation nodes for zombies for an image of a map. I can make it available and write some instructions if you like, but it just crashed on me and I need to fix it first.

**Comment by dille12** [comment]
> endless mode seems pretty cool it ran it played but on exit was errors and on loading timeout issues but selecting wait worked also endless i think could benifit from a larger map? could you give me a quick run down on the game structure? i know your using pygame never used it before but i would like to add to it also a "take all" would be cool in treasure box menu :
> 
> ```
>  Traceback (most recent call last):
>   File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1369, in <module>
>     main()
>   File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 1261, in main
>     s7_2 = button_start_single_player.tick(screen, mouse_pos, mouse_single_tick, glitch)
>   File "/home/xanth/Desktop/OVRDOZE-main/button.py", line 134, in tick
>     return self.action(arg) if arg != None else self.action(self.args)
>   File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 395, in start_sp
>     app.start_sp(args)
>   File "/home/xanth/Desktop/OVRDOZE-main/app.py", line 271, in start_sp
>     game.main(
>   File "/home/xanth/Desktop/OVRDOZE-main/game.py", line 2169, in main
>     quit_button_alt.tick(screen, mouse_pos, click_single_tick, glitch)
>   File "/home/xanth/Desktop/OVRDOZE-main/button.py", line 134, in tick
>     return self.action(arg) if arg != None else self.action(self.args)
>   File "/home/xanth/Desktop/OVRDOZE-main/game.py", line 82, in quit
>     RUN.main()
>   File "/home/xanth/Desktop/OVRDOZE-main/RUN.py", line 984, in main
>     if app.pygame.mouse.get_pressed()[0] and clicked == False:
> UnboundLocalError: local variable 'clicked' referenced before assignment
> ```

Sorry I didn't see this, and thank you for bringing up the bug and the suggestions, I do agree with them. If you're still interested I can tell you more about the structure
